"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.decisioning.v2.customers.reports.balance_analytics import (
    AsyncBalanceAnalyticsClient,
    BalanceAnalyticsClient,
)
from open_banking.resources.decisioning.v2.customers.reports.cashflow_analytics import (
    AsyncCashflowAnalyticsClient,
    CashflowAnalyticsClient,
)


class ReportsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.balance_analytics = BalanceAnalyticsClient(base_client=self._base_client)
        self.cashflow_analytics = CashflowAnalyticsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncReportsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.balance_analytics = AsyncBalanceAnalyticsClient(
            base_client=self._base_client
        )
        self.cashflow_analytics = AsyncCashflowAnalyticsClient(
            base_client=self._base_client
        )

    # register async api methods (keep comment for code generation)
