"""File Generated by Sideko (sideko.dev)"""

from .resource_client import InstitutionLoginsClient, AsyncInstitutionLoginsClient


__all__ = ["InstitutionLoginsClient", "AsyncInstitutionLoginsClient"]
