"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.decisioning.v3.customers.reports import (
    ReportsClient,
    AsyncReportsClient,
)


class CustomersClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.reports = ReportsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncCustomersClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.reports = AsyncReportsClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
