"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.connect.v2.generate import (
    AsyncGenerateClient,
    GenerateClient,
)
from open_banking.resources.connect.v2.send import AsyncSendClient, SendClient


class V2Client:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.generate = GenerateClient(base_client=self._base_client)
        self.send = SendClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncV2Client:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.generate = AsyncGenerateClient(base_client=self._base_client)
        self.send = AsyncSendClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
