"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    SyncBaseClient,
    AsyncBaseClient,
    to_encodable,
    RequestOptions,
    default_request_options,
)
from open_banking.types.aggregation.v2.customers.active import models, params
import typing


class ActiveClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.NewCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CreatedCustomer:
        """
        Enroll an active customer, which is the actual owner of one or more real-world accounts. This is a billable customer.

        Active customers must use the "FinBank Billable" profiles for testing purposes.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerNewCustomer)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/aggregation/v2/customers/active",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.CreatedCustomer,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncActiveClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.NewCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CreatedCustomer:
        """
        Enroll an active customer, which is the actual owner of one or more real-world accounts. This is a billable customer.

        Active customers must use the "FinBank Billable" profiles for testing purposes.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerNewCustomer)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/aggregation/v2/customers/active",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.CreatedCustomer,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
