"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.aggregation.v1 import AsyncV1Client, V1Client
from open_banking.resources.aggregation.v2 import AsyncV2Client, V2Client
from open_banking.resources.aggregation.v3 import AsyncV3Client, V3Client
from open_banking.resources.aggregation.v4 import AsyncV4Client, V4Client


class AggregationClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.v1 = V1Client(base_client=self._base_client)
        self.v2 = V2Client(base_client=self._base_client)
        self.v3 = V3Client(base_client=self._base_client)
        self.v4 = V4Client(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncAggregationClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.v1 = AsyncV1Client(base_client=self._base_client)
        self.v2 = AsyncV2Client(base_client=self._base_client)
        self.v3 = AsyncV3Client(base_client=self._base_client)
        self.v4 = AsyncV4Client(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
