"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    to_encodable,
    default_request_options,
    RequestOptions,
    SyncBaseClient,
    AsyncBaseClient,
)
from open_banking.types.connect.v2.generate.joint_borrower import params, models
import typing


class JointBorrowerClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.ConnectJointBorrowerParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectUrl:
        """
        Same as Connect Full (`POST /connect/v2/generate`) but for joint borrowers.

        MVS prompts both the primary and joint borrower to enter each of their financial, payroll, and paystub information in the same Connect session.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerConnectJointBorrowerParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/connect/v2/generate/jointBorrower",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncJointBorrowerClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.ConnectJointBorrowerParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectUrl:
        """
        Same as Connect Full (`POST /connect/v2/generate`) but for joint borrowers.

        MVS prompts both the primary and joint borrower to enter each of their financial, payroll, and paystub information in the same Connect session.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerConnectJointBorrowerParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/connect/v2/generate/jointBorrower",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
