"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.aggregation.v2.customers.institution_logins.accounts import (
    AsyncAccountsClient,
    AccountsClient,
)
from open_banking.resources.aggregation.v2.customers.institution_logins.migration import (
    AsyncMigrationClient,
    MigrationClient,
)


class InstitutionLoginsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.accounts = AccountsClient(base_client=self._base_client)
        self.migration = MigrationClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncInstitutionLoginsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.accounts = AsyncAccountsClient(base_client=self._base_client)
        self.migration = AsyncMigrationClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
