"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PartnerCredentials(typing_extensions.TypedDict):
    """
    No description specified
    """

    partner_id: typing_extensions.Required[str]
    partner_secret: typing_extensions.Required[str]


class _SerializerPartnerCredentials(pydantic.BaseModel):
    """
    Serializer for PartnerCredentials handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    partner_id: str = pydantic.Field(alias="partnerId")
    partner_secret: str = pydantic.Field(alias="partnerSecret")
