"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import AsyncBaseClient, SyncBaseClient
from open_banking.resources.aggregation.v2.partners.applications import (
    AsyncApplicationsClient,
    ApplicationsClient,
)
from open_banking.resources.aggregation.v2.partners.authentication import (
    AsyncAuthenticationClient,
    AuthenticationClient,
)


class PartnersClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.applications = ApplicationsClient(base_client=self._base_client)
        self.authentication = AuthenticationClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncPartnersClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.applications = AsyncApplicationsClient(base_client=self._base_client)
        self.authentication = AsyncAuthenticationClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
