"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import AsyncBaseClient, SyncBaseClient
from open_banking.resources.aggregation.v4.customers import (
    AsyncCustomersClient,
    CustomersClient,
)


class V4Client:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.customers = CustomersClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncV4Client:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.customers = AsyncCustomersClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
