"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import AsyncBaseClient, SyncBaseClient
from open_banking.resources.business_services.businesses import (
    AsyncBusinessesClient,
    BusinessesClient,
)
from open_banking.resources.business_services.customers import (
    CustomersClient,
    AsyncCustomersClient,
)


class BusinessServicesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.businesses = BusinessesClient(base_client=self._base_client)
        self.customers = CustomersClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncBusinessServicesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.businesses = AsyncBusinessesClient(base_client=self._base_client)
        self.customers = AsyncCustomersClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
