"""File Generated by Sideko (sideko.dev)"""

from .resource_client import AsyncAuthorizationDetailsClient, AuthorizationDetailsClient


__all__ = ["AsyncAuthorizationDetailsClient", "AuthorizationDetailsClient"]
