"""File Generated by Sideko (sideko.dev)"""

from .resource_client import (
    AsyncCertifiedInstitutionsClient,
    CertifiedInstitutionsClient,
)


__all__ = ["AsyncCertifiedInstitutionsClient", "CertifiedInstitutionsClient"]
