"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    default_request_options,
    AsyncBaseClient,
    RequestOptions,
    to_encodable,
    SyncBaseClient,
)
from open_banking.resources.connect.v2.send.email_resource.joint_borrower import (
    AsyncJointBorrowerClient,
    JointBorrowerClient,
)
from open_banking.types.connect.v2.send.email_resource import params, models
import typing


class EmailClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.joint_borrower = JointBorrowerClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.ConnectEmailParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectEmailUrl:
        """
        Same as Connect Full (`POST /connect/v2/generate`) but send a Connect email to a consumer.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerConnectEmailParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/connect/v2/send/email",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectEmailUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncEmailClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.joint_borrower = AsyncJointBorrowerClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.ConnectEmailParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectEmailUrl:
        """
        Same as Connect Full (`POST /connect/v2/generate`) but send a Connect email to a consumer.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerConnectEmailParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/connect/v2/send/email",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectEmailUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
