"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    default_request_options,
    AsyncBaseClient,
    RequestOptions,
    SyncBaseClient,
)
import typing
from open_banking.types.decisioning.v1.customers.portfolios import models


class PortfoliosClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        customer_id: str,
        portfolio_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PortfolioSummary:
        """
        Return a portfolio of most recently generated reports for each report type for the given customer. If there are multiple reports that were generated for a report type (VOA, VOI, etc.), only the most recently generated report for the type will be returned.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)

        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/decisioning/v1/customers/{customer_id}/portfolios/{portfolio_id}",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            cast_to=models.PortfolioSummary,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncPortfoliosClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        customer_id: str,
        portfolio_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PortfolioSummary:
        """
        Return a portfolio of most recently generated reports for each report type for the given customer. If there are multiple reports that were generated for a report type (VOA, VOI, etc.), only the most recently generated report for the type will be returned.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)

        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/decisioning/v1/customers/{customer_id}/portfolios/{portfolio_id}",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            cast_to=models.PortfolioSummary,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
