"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import AsyncBaseClient, SyncBaseClient
from open_banking.resources.customers.institution_logins import (
    InstitutionLoginsClient,
    AsyncInstitutionLoginsClient,
)


class CustomersClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.institution_logins = InstitutionLoginsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncCustomersClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.institution_logins = AsyncInstitutionLoginsClient(
            base_client=self._base_client
        )

    # register async api methods (keep comment for code generation)
