"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class Branding(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    alternate_logo: typing.Optional[str] = pydantic.Field(
        alias="alternateLogo", default=None
    )
    icon: typing.Optional[str] = pydantic.Field(alias="icon", default=None)
    logo: typing.Optional[str] = pydantic.Field(alias="logo", default=None)
    primary_color: typing.Optional[str] = pydantic.Field(
        alias="primaryColor", default=None
    )
    tile: typing.Optional[str] = pydantic.Field(alias="tile", default=None)


class BrandingWrapper(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    branding: Branding = pydantic.Field(alias="branding")
