"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    QueryParams,
    RequestOptions,
    SyncBaseClient,
    encode_param,
    default_request_options,
    AsyncBaseClient,
)
import typing
from open_banking.types.institution.v2.certified_institutions.rssd import models


class RssdClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        start: typing.Optional[int] = None,
        supported_countries: typing.Optional[typing.List[str]] = None,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CertifiedInstitutions:
        """
        Search for certified financial institutions w/RSSD.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if search is not None:
            _query["search"] = encode_param(search, False)
        if start is not None:
            _query["start"] = encode_param(start, False)
        if supported_countries is not None:
            _query["supportedCountries"] = encode_param(supported_countries, False)
        if type is not None:
            _query["type"] = encode_param(type, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/institution/v2/certifiedInstitutions/rssd",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            query_params=_query,
            cast_to=models.CertifiedInstitutions,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncRssdClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        start: typing.Optional[int] = None,
        supported_countries: typing.Optional[typing.List[str]] = None,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CertifiedInstitutions:
        """
        Search for certified financial institutions w/RSSD.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if search is not None:
            _query["search"] = encode_param(search, False)
        if start is not None:
            _query["start"] = encode_param(start, False)
        if supported_countries is not None:
            _query["supportedCountries"] = encode_param(supported_countries, False)
        if type is not None:
            _query["type"] = encode_param(type, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/institution/v2/certifiedInstitutions/rssd",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            query_params=_query,
            cast_to=models.CertifiedInstitutions,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
