"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    SyncBaseClient,
    to_encodable,
    default_request_options,
    RequestOptions,
    AsyncBaseClient,
)
from open_banking.types.connect.v2.generate.fix import params, models
import typing


class FixClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.FixConnectParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectUrl:
        """
        Use the Connect Fix API when the following conditions occur:
        * The connection to the user's financial institution is lost
        * The user's credentials were updated (for any number of reasons)
        * The user's MFA challenge has expired

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerFixConnectParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/connect/v2/generate/fix",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncFixClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.FixConnectParameters,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ConnectUrl:
        """
        Use the Connect Fix API when the following conditions occur:
        * The connection to the user's financial institution is lost
        * The user's credentials were updated (for any number of reasons)
        * The user's MFA challenge has expired

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerFixConnectParameters
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/connect/v2/generate/fix",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.ConnectUrl,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
