"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class AvailableBalance(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    aggregation_status_code: int = pydantic.Field(alias="aggregationStatusCode")
    available_balance: float = pydantic.Field(alias="availableBalance")
    available_balance_date: int = pydantic.Field(alias="availableBalanceDate")
    cleared_balance: float = pydantic.Field(alias="clearedBalance")
    cleared_balance_date: int = pydantic.Field(alias="clearedBalanceDate")
    currency: str = pydantic.Field(alias="currency")
    id: int = pydantic.Field(alias="id")
    real_account_number_last4: str = pydantic.Field(alias="realAccountNumberLast4")
