"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    AsyncBaseClient,
    default_request_options,
    RequestOptions,
    SyncBaseClient,
)
import typing
from open_banking.types.aggregation.v2.customers.transactions import models


class TransactionsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        customer_id: str,
        transaction_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Transaction:
        """
        Get details for the given transaction.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/aggregation/v2/customers/{customer_id}/transactions/{transaction_id}",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            cast_to=models.Transaction,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncTransactionsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        customer_id: str,
        transaction_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Transaction:
        """
        Get details for the given transaction.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/aggregation/v2/customers/{customer_id}/transactions/{transaction_id}",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            cast_to=models.Transaction,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
