"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    SyncBaseClient,
    AsyncBaseClient,
    default_request_options,
    RequestOptions,
    to_encodable,
)
from open_banking.types.aggregation.v2.customers.testing import models, params
import typing


class TestingClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.NewCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CreatedCustomer:
        """
        Enroll a testing customer (Test Drive accounts).

        For using testing customers with FinBank OAuth, you must register a test application with your systems engineer or account manager. Then, use that testing `applicationId` when creating testing customers.

        Testing Customers can access FinBank profiles (except "FinBank Billable" profiles), and cannot access live financial institutions.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerNewCustomer)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/aggregation/v2/customers/testing",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.CreatedCustomer,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncTestingClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.NewCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CreatedCustomer:
        """
        Enroll a testing customer (Test Drive accounts).

        For using testing customers with FinBank OAuth, you must register a test application with your systems engineer or account manager. Then, use that testing `applicationId` when creating testing customers.

        Testing Customers can access FinBank profiles (except "FinBank Billable" profiles), and cannot access live financial institutions.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerNewCustomer)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/aggregation/v2/customers/testing",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            json=_json,
            cast_to=models.CreatedCustomer,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
