"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class MicroDepositVerification(typing_extensions.TypedDict):
    """
    A list of amounts
    """

    amounts: typing_extensions.Required[typing.List[float]]


class _SerializerMicroDepositVerification(pydantic.BaseModel):
    """
    Serializer for MicroDepositVerification handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    amounts: typing.List[float] = pydantic.Field(alias="amounts")
