"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.decisioning.v2.customers.asset_summary import (
    AssetSummaryClient,
    AsyncAssetSummaryClient,
)
from open_banking.resources.decisioning.v2.customers.cash_flow_business import (
    CashFlowBusinessClient,
    AsyncCashFlowBusinessClient,
)
from open_banking.resources.decisioning.v2.customers.cash_flow_personal import (
    CashFlowPersonalClient,
    AsyncCashFlowPersonalClient,
)
from open_banking.resources.decisioning.v2.customers.pay_statement import (
    AsyncPayStatementClient,
    PayStatementClient,
)
from open_banking.resources.decisioning.v2.customers.pre_qual_voa import (
    AsyncPreQualVoaClient,
    PreQualVoaClient,
)
from open_banking.resources.decisioning.v2.customers.reports import (
    AsyncReportsClient,
    ReportsClient,
)
from open_banking.resources.decisioning.v2.customers.statement import (
    AsyncStatementClient,
    StatementClient,
)
from open_banking.resources.decisioning.v2.customers.transactions import (
    TransactionsClient,
    AsyncTransactionsClient,
)
from open_banking.resources.decisioning.v2.customers.voa import (
    AsyncVoaClient,
    VoaClient,
)
from open_banking.resources.decisioning.v2.customers.voa_history import (
    VoaHistoryClient,
    AsyncVoaHistoryClient,
)
from open_banking.resources.decisioning.v2.customers.voe_payroll import (
    AsyncVoePayrollClient,
    VoePayrollClient,
)
from open_banking.resources.decisioning.v2.customers.voe_transactions import (
    AsyncVoeTransactionsClient,
    VoeTransactionsClient,
)
from open_banking.resources.decisioning.v2.customers.voi import (
    AsyncVoiClient,
    VoiClient,
)
from open_banking.resources.decisioning.v2.customers.voie_payroll import (
    VoiePayrollClient,
    AsyncVoiePayrollClient,
)
from open_banking.resources.decisioning.v2.customers.voie_tx_verify import (
    AsyncVoieTxVerifyClient,
    VoieTxVerifyClient,
)


class CustomersClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.asset_summary = AssetSummaryClient(base_client=self._base_client)
        self.cash_flow_business = CashFlowBusinessClient(base_client=self._base_client)
        self.cash_flow_personal = CashFlowPersonalClient(base_client=self._base_client)
        self.pay_statement = PayStatementClient(base_client=self._base_client)
        self.pre_qual_voa = PreQualVoaClient(base_client=self._base_client)
        self.reports = ReportsClient(base_client=self._base_client)
        self.statement = StatementClient(base_client=self._base_client)
        self.transactions = TransactionsClient(base_client=self._base_client)
        self.voa = VoaClient(base_client=self._base_client)
        self.voa_history = VoaHistoryClient(base_client=self._base_client)
        self.voe_payroll = VoePayrollClient(base_client=self._base_client)
        self.voe_transactions = VoeTransactionsClient(base_client=self._base_client)
        self.voi = VoiClient(base_client=self._base_client)
        self.voie_payroll = VoiePayrollClient(base_client=self._base_client)
        self.voie_tx_verify = VoieTxVerifyClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncCustomersClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.asset_summary = AsyncAssetSummaryClient(base_client=self._base_client)
        self.cash_flow_business = AsyncCashFlowBusinessClient(
            base_client=self._base_client
        )
        self.cash_flow_personal = AsyncCashFlowPersonalClient(
            base_client=self._base_client
        )
        self.pay_statement = AsyncPayStatementClient(base_client=self._base_client)
        self.pre_qual_voa = AsyncPreQualVoaClient(base_client=self._base_client)
        self.reports = AsyncReportsClient(base_client=self._base_client)
        self.statement = AsyncStatementClient(base_client=self._base_client)
        self.transactions = AsyncTransactionsClient(base_client=self._base_client)
        self.voa = AsyncVoaClient(base_client=self._base_client)
        self.voa_history = AsyncVoaHistoryClient(base_client=self._base_client)
        self.voe_payroll = AsyncVoePayrollClient(base_client=self._base_client)
        self.voe_transactions = AsyncVoeTransactionsClient(
            base_client=self._base_client
        )
        self.voi = AsyncVoiClient(base_client=self._base_client)
        self.voie_payroll = AsyncVoiePayrollClient(base_client=self._base_client)
        self.voie_tx_verify = AsyncVoieTxVerifyClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
