"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import (
    default_request_options,
    SyncBaseClient,
    AsyncBaseClient,
    RequestOptions,
    QueryParams,
    encode_param,
)
import typing
from open_banking.types.aggregation.v3.customers.accounts.statement import models


class StatementClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        customer_id: str,
        account_id: str,
        index: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CustomerAccountMultipleStatements:
        """
        This endpoint retrieves account statements for a given customer. The maximum number of statements that can be returned is 24.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if index is not None:
            _query["index"] = encode_param(index, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/aggregation/v3/customers/{customer_id}/accounts/{account_id}/statement",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            query_params=_query,
            cast_to=models.CustomerAccountMultipleStatements,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncStatementClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        customer_id: str,
        account_id: str,
        index: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.CustomerAccountMultipleStatements:
        """
        This endpoint retrieves account statements for a given customer. The maximum number of statements that can be returned is 24.

        _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if index is not None:
            _query["index"] = encode_param(index, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/aggregation/v3/customers/{customer_id}/accounts/{account_id}/statement",
            auth_names=["FinicityAppKey", "FinicityAppToken"],
            query_params=_query,
            cast_to=models.CustomerAccountMultipleStatements,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
