"""File Generated by Sideko (sideko.dev)"""

from open_banking.core import SyncBaseClient, AsyncBaseClient
from open_banking.resources.decisioning.v3.consumers import (
    ConsumersClient,
    AsyncConsumersClient,
)
from open_banking.resources.decisioning.v3.customers import (
    CustomersClient,
    AsyncCustomersClient,
)


class V3Client:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.consumers = ConsumersClient(base_client=self._base_client)
        self.customers = CustomersClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncV3Client:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.consumers = AsyncConsumersClient(base_client=self._base_client)
        self.customers = AsyncCustomersClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
